/*crear el usuario*/

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER INARTECT_ IDENTIFIED BY Pa55w0rd
      DEFAULT TABLESPACE INARTECT_
      TEMPORARY TABLESPACE temp
      QUOTA UNLIMITED ON INARTECT_;
      
GRANT ALL PRIVILEGES TO INARTECT_; /*se asignaron todos lo privilegios */
      
/* --------- crear tablas y llaves ------------- */

/*  Crear tabla productos */
CREATE TABLE PRODUCTOS(
    ID_PRODUCTO NUMBER GENERATED ALWAYS AS IDENTITY,
    CODIGO VARCHAR(10),
    NOMBRE VARCHAR(255),
    PROVEEDOR NUMBER(3),
    VALOR NUMBER(5,2),
    EXISTENCIA NUMBER(5,2)
);
ALTER TABLE PRODUCTOS ADD CONSTRAINT PRODUCTOS_pk PRIMARY KEY (ID_PRODUCTO);

/*  Crear tabla PROVEEDORES */
CREATE TABLE PROVEEDORES(
    ID_PROVEEDORES NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(25),
    CORREO VARCHAR(25)
);
ALTER TABLE PROVEEDORES ADD CONSTRAINT PROVEEDORES_pk PRIMARY KEY (ID_PROVEEDORES);
insert into proveedores (nombre,direccion,telefono,correo) values ('proveedor1','san salvador #129','25477896','correo@ejemplo.com')

/*  Crear tabla historico */
/* TIPO E ENTRADA, TIPO S SALIDA */
CREATE TABLE HISTORICO(
    ID_HISTORICO NUMBER GENERATED ALWAYS AS IDENTITY,
    CODIGO_PRODUCTO VARCHAR(10),
    CANT_MOV NUMBER(4),
    TIPO   VARCHAR(1),
    FECHA DATE
);

ALTER TABLE HISTORICO ADD CONSTRAINT HISTORICO_pk PRIMARY KEY (ID_HISTORICO);

/* Agregando las llaves foranea */

ALTER TABLE PRODUCTOS
ADD CONSTRAINT PRODUCTOS_uniques UNIQUE (CODIGO);



ALTER TABLE HISTORICO
ADD CONSTRAINT FK_to_PRODUCTOS
   FOREIGN KEY (CODIGO_PRODUCTO)
   REFERENCES PRODUCTOS (CODIGO);
   
   ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_to_PROVEEDORES
   FOREIGN KEY (PROVEEDOR)
   REFERENCES PROVEEDORES (ID_PROVEEDORES);
   
   
/*  PROCEDIMIENTOS  */

